# Generated by Django 2.2.3 on 2019-08-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190804_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
