# Generated by Django 2.2.3 on 2019-08-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190804_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rep',
            field=models.IntegerField(default=0),
        ),
    ]
