# Generated by Django 2.2.3 on 2019-10-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coin_address',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='coin_address_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
