# Generated by Django 2.2.3 on 2019-09-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, unique=True)),
                ('votes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('voted', models.CharField(default='', max_length=10000)),
                ('sender', models.CharField(max_length=150)),
                ('body', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
