# Generated by Django 2.2.3 on 2019-09-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('sender', models.CharField(max_length=150)),
                ('post_id', models.CharField(max_length=1000)),
            ],
        ),
    ]
