# Generated by Django 2.2.3 on 2019-09-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20190929_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
