# Generated by Django 2.2.3 on 2019-10-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_reply_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='voted',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='voted',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
    ]
