# Generated by Django 2.2.3 on 2019-10-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20191006_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
