# Generated by Django 2.2.3 on 2019-09-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='sender',
            field=models.CharField(default='JonPizza', max_length=150),
            preserve_default=False,
        ),
    ]
