# Generated by Django 2.2.3 on 2019-09-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0002_img_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='body',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='img',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='img',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='img',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
