# Generated by Django 2.2.3 on 2019-09-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0003_auto_20190922_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='voted',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
