# Generated by Django 2.2.3 on 2019-08-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('short_desc', models.CharField(max_length=150)),
                ('long_desc', models.CharField(max_length=1000)),
            ],
        ),
    ]
