# Generated by Django 2.2.3 on 2019-08-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.CharField(default='3', max_length=1),
        ),
    ]
