# Generated by Django 2.2.3 on 2019-08-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.CharField(max_length=1),
        ),
    ]
