# Generated by Django 2.2.3 on 2019-08-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190804_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rating',
        ),
        migrations.AddField(
            model_name='item',
            name='github_link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='item',
            name='long_desc',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
