# Generated by Django 2.2.3 on 2019-08-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190804_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='language',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='short_desc',
            field=models.CharField(max_length=500),
        ),
    ]
