# Generated by Django 2.2.3 on 2019-08-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190804_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
