# Generated by Django 2.2.3 on 2019-08-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190804_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='github_link',
        ),
        migrations.AddField(
            model_name='item',
            name='project_link',
            field=models.URLField(default='https://jon.network'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='voted',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
