# Generated by Django 2.2.3 on 2019-08-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190805_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='voted',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
