# Generated by Django 2.2.3 on 2019-08-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20190805_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='long_desc',
            field=models.TextField(max_length=20000),
        ),
    ]
