# Generated by Django 2.2.3 on 2019-08-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190809_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='project_link',
            field=models.URLField(blank=True),
        ),
    ]
