# Generated by Django 2.2.3 on 2019-09-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20190930_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=150)),
                ('body', models.TextField(max_length=2000)),
                ('to_item', models.IntegerField()),
            ],
        ),
    ]
