# Generated by Django 2.2.3 on 2019-09-30 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
