# Generated by Django 2.2.3 on 2019-10-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='catagory',
            field=models.CharField(default='bitcoin', max_length=100),
            preserve_default=False,
        ),
    ]
