# Generated by Django 2.2.3 on 2019-10-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='domain',
            field=models.CharField(default='jon.network', max_length=100),
            preserve_default=False,
        ),
    ]
